
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly

matrix:
  allow_failures:
    - php: 7.0

env:
    global:
      - REPORT_EXIT_STATUS=1
      - USE_VALGRIND=1
    matrix:
      - ENABLE_MAINTAINER_ZTS=0 ENABLE_DEBUG=0
      - ENABLE_MAINTAINER_ZTS=1 ENABLE_DEBUG=1
      - ENABLE_MAINTAINER_ZTS=1 ENABLE_DEBUG=1 USE_ZEND_ALLOC=0

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes valgrind

script: sh travis/run-test.sh
